WebApp/Foosball/Foosball/Controllers/GoalsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Foosball.Models;
using Foosball.Broadcasters;
using Microsoft.AspNetCore.Authorization;

namespace Foosball.Controllers
{
    public class GoalsController : Controller
    {
        private readonly FoosballContext _context;

        public GoalsController(FoosballContext context)
        {
            _context = context;
        }

        [Authorize]
        public IActionResult Admin()
        {
            return View();
        }
    }
}

WebApp/Foosball/Foosball/Controllers/MatchesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Foosball.Models;
using Microsoft.AspNetCore.Authorization;

namespace Foosball.Controllers
{
    public class MatchesController : Controller
    {
        private readonly FoosballContext _context;

        public MatchesController(FoosballContext context)
        {
            _context = context;
        }

        [Authorize]
        public IActionResult Admin()
        {
            return View();
        }
    }
}

WebApp/Foosball/Foosball/Controllers/PlayersController.cs
using Foosball.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;

namespace Foosball.Controllers
{
    public class PlayersController : Controller
    {
        private readonly FoosballContext _context;

        public PlayersController(FoosballContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var idQuery = _context.Rating
                .GroupBy(r => r.PlayerId)
                .Select(g => g.OrderByDescending(r => r.LastUpdatedAt).FirstOrDefault())
                .OrderByDescending(r => r.ELO)
                .Select(r => r.Id);

            var players = _context.Rating
                .Include("Player")
                .Where(r => idQuery.Contains(r.Id))
                .OrderByDescending(r => r.ELO)
                .Where(r => r.PlayerId > 0)
                .Select(r => new Rating
                {
                    ELO = r.ELO,
                    Player = new Player
                    {
                        Id = r.Player.Id,
                        Name = r.Player.Name
                    }
                });

            return View(players);
        }

        public IActionResult Profile(int id)
        {
            var player = _context.Player
                .Where(p => p.Id == id)
                .FirstOrDefault();

            if (player == null)
                return BadRequest("Invalid Player ID");

            ViewData["Player"] = player;

            ViewData["Ratings"] = _context.Rating
                .Where(r => r.PlayerId == id)
                .Select(r => new Rating
                {
                    PlayerId = r.PlayerId,
                    ELO = r.ELO,
                    CreatedAt = r.CreatedAt,
                    LastUpdatedAt = r.LastUpdatedAt
                });

            var teams = _context.Team
                .Include(t => t.PlayerOne)
                .Include(t => t.PlayerTwo)
                .Where(p => p.PlayerOneId == id || p.PlayerTwoId == id);

            ViewData["Teams"] = teams;

            var idQuery = teams.Select(r => r.Id);

            ViewData["TeamMatches"] = _context.Match
                .Where(m => m.State == MatchState.Completed)
                .Include(m => m.Goals)
                .Include(m => m.TeamBlack)
                    .ThenInclude(t => t.PlayerOne)
                .Include(m => m.TeamBlack)
                    .ThenInclude(t => t.PlayerTwo)
                .Include(m => m.TeamGrey)
                    .ThenInclude(t => t.PlayerOne)
                .Include(m => m.TeamGrey)
                    .ThenInclude(t => t.PlayerTwo)
                .Take(10)
                .Where(r => idQuery.Contains(r.Id));

            return View();
        }

        [Authorize]
        public IActionResult Admin()
        {
            return View();
        }
    }
}

WebApp/Foosball/Foosball/Controllers/TeamsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Foosball.Models;
using Microsoft.AspNetCore.Authorization;

namespace Foosball.Controllers
{
    public class TeamsController : Controller
    {
        private readonly FoosballContext _context;

        public TeamsController(FoosballContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var idQuery = _context.Rating
                .GroupBy(r => r.TeamId)
                .Select(g => g.OrderByDescending(r => r.LastUpdatedAt).FirstOrDefault())
                .OrderByDescending(r => r.ELO)
                .Select(r => r.Id);

            var teams = _context.Rating
                .Include(r => r.Team)
                    .ThenInclude(t => t.PlayerOne)
                .Include(r => r.Team)
                    .ThenInclude(t => t.PlayerTwo)
                .Where(r => idQuery.Contains(r.Id))
                .OrderByDescending(r => r.ELO)
                .Where(r => r.TeamId > 0)
                .Select(r => new Rating
                {
                    ELO = r.ELO,
                    Team = new Team
                    {
                        Id = r.Team.Id,
                        PlayerOne = new Player {
                            Name = r.Team.PlayerOne.Name
                        },
                        PlayerTwo = new Player
                        {
                            Name = r.Team.PlayerTwo.Name
                        }
                    }
                });

            return View(teams);
        }

        public IActionResult Profile(int id)
        {            
            var team = _context.Team
                .Include(t => t.PlayerOne)
                .Include(t => t.PlayerTwo)
                .Where(p => p.Id == id)
                .Select(t => new Team
                {
                    Id = t.Id,
                    PlayerOne = new Player
                    {
                        Name = t.PlayerOne.Name
                    },
                    PlayerTwo = new Player
                    {
                        Name = t.PlayerTwo.Name
                    }
                })
                .FirstOrDefault();

            if (team == null)
                return BadRequest("Invalid Team ID");

            ViewData["Team"] = team;

            ViewData["Ratings"] = _context.Rating
                .Where(r => r.TeamId == id)
                .Select(r => new Rating
                {
                    TeamId = r.TeamId,
                    ELO = r.ELO,
                    CreatedAt = r.CreatedAt,
                    LastUpdatedAt = r.LastUpdatedAt
                });                       

            ViewData["TeamMatches"] = _context.Match
                .Where(m => m.State == MatchState.Completed)
                .Include(m => m.Goals)
                .Include(m => m.TeamBlack)
                    .ThenInclude(t => t.PlayerOne)
                .Include(m => m.TeamBlack)
                    .ThenInclude(t => t.PlayerTwo)
                .Include(m => m.TeamGrey)
                    .ThenInclude(t => t.PlayerOne)
                .Include(m => m.TeamGrey)
                    .ThenInclude(t => t.PlayerTwo)
                .Take(10)
                .Where(r => r.TeamBlackId == id || r.TeamGreyId == id);

            return View();
        }

        [Authorize]
        public IActionResult Admin()
        {
            return View();
        }
    }
}

WebApp/Foosball/Foosball/Views/Shared/Layout/_Navigation.cshtml
<h3>Menu</h3>
<ul class="nav side-menu">
    <li><a asp-area="" asp-controller="Home" asp-action="Index"><i class="fa fa-desktop"></i>&nbsp;Dashboard</a></li>
    <li><a asp-area="" asp-controller="Players" asp-action="Index"><i class="fa fa-user"></i>&nbsp;Players</a></li>
    <li><a asp-area="" asp-controller="Teams" asp-action="Index"><i class="fa fa-users"></i>&nbsp;Teams</a></li>

    @if (User.Identity.IsAuthenticated)
    {
        <li>
            <a><i class="fa fa-lock"></i> Admin <span class="fa fa-chevron-down"></span></a>
            <ul class="nav child_menu" style="">
                <li><a asp-area="" asp-controller="Players" asp-action="Admin">Players</a></li>
                <li><a asp-area="" asp-controller="Teams" asp-action="Admin">Teams</a></li>
                <li><a asp-area="" asp-controller="Matches" asp-action="Admin">Matches</a></li>
                <li><a asp-area="" asp-controller="Goals" asp-action="Admin">Goals</a></li>
                <li><a asp-area="" asp-controller="Ratings" asp-action="Admin">Ratings</a></li>
            </ul>
        </li>

        <li><a href="\Swagger"><i class="fa fa-server"></i>&nbsp;Swagger API</a></li>
    }
</ul>

WebApp/Foosball/Foosball/Views/Shared/Layout/_Sidebar.cshtml
<div class="left_col scroll-view">
    <div class="navbar nav_title" style="border: 0; height: initial;">
        <!--<img src="~/images/RVB_ALTRAN_10CM.jpg" style="width: 100%;"/>-->
    </div>

    <div class="clearfix"></div>

    <!-- sidebar menu -->
    <div id="sidebar-menu" class="main_menu_side hidden-print main_menu" style="margin-top:20px;">
        <div class="menu_section">
            @{Html.RenderPartial("Layout/_Navigation");}
        </div>
    </div>
    <!-- /sidebar menu -->
    <!-- /menu footer buttons -->
    <div class="sidebar-footer">
        <!--<a data-toggle="tooltip" data-placement="top" title="Settings">
            <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
        </a>
        <a data-toggle="tooltip" data-placement="top" title="FullScreen">
            <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
        </a>
        <a data-toggle="tooltip" data-placement="top" title="Lock">
            <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
        </a>-->
        @if (User.Identity.IsAuthenticated)
        {
            <a style="width:100%;" data-toggle="tooltip" data-placement="top" title="Logout" asp-controller="Account" asp-action="Logout">
                <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span>
            </a>
        }
        else
        {
            <a style="width:100%;" data-toggle="tooltip" data-placement="top" title="Login" asp-controller="Account" asp-action="Login">
                <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>
            </a>
        }
    </div>
</div>

WebApp/Foosball/Foosball/Views/Shared/Layout/_Siren.cshtml
<div id="siren-container" style="display:none;">
    <center>
        <div class="lightbar">
            <div id="light-1" class="light strobe blue">
                <div class="inner-light"></div>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
            </div>
            <div id="light-2" class="light strobe blue">
                <div class="inner-light"></div>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
            </div>
            <div id="light-3" class="light strobe blue">
                <div class="inner-light"></div>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
            </div>
            <div id="light-4" class="light strobe red delay">
                <div class="inner-light"></div>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
            </div>
            <div id="light-5" class="light strobe red delay">
                <div class="inner-light"></div>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
            </div>
            <div id="light-6" class="light strobe red delay">
                <div class="inner-light"></div>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
                <span class="bulb"></span>
            </div>
        </div>
    </center>
</div>

<script>
    function activateSiren() {
        $('#siren-container').show();
        $('.light').attr('class', 'light');
        setTimeout(function () {
            $('#light-1, #light-2, #light-3').attr('class', 'light strobe blue');
            $('#light-4, #light-5, #light-6').attr('class', 'light strobe red delay');
        }, 50);
    }
    $('.light').attr('class', 'light');
</script>